'use client';
import { useEffect,useState } from "react";
const freshForm=()=>({dossier:"004",title:"",hook:"",platform:"YouTube Shorts",views:0,likes:0,comments:0,shares:0,retention:"",completion:"",scrollStop:"",followers:0,publishedAt:new Date().toISOString().slice(0,16)});
const freshSnap=()=>({project:"Dossier Noir",dossier:"005",hours:"1",platform:"YouTube Shorts",views:0,likes:0,comments:0,shares:0,scrollStop:"",retention:"",completion:"",avgViewDuration:"",followers:0,shownInFeed:""});
const checkpoints=["1","3","6","12","24","48","72","168"];
export default function AdminPage(){
 const [entries,setEntries]=useState([]),[snapshots,setSnapshots]=useState([]),[margeSnapshots,setMargeSnapshots]=useState([]),[form,setForm]=useState(freshForm()),[snap,setSnap]=useState(freshSnap());
 useEffect(()=>{try{setEntries(JSON.parse(localStorage.getItem("dn-manual-v4")||localStorage.getItem("dn-manual-v3")||"[]"));setSnapshots(JSON.parse(localStorage.getItem("dn-snapshots-v43")||"[]"));setMargeSnapshots(JSON.parse(localStorage.getItem("marge-snapshots-v1")||"[]"))}catch{}},[]);
 const save=(x)=>{setEntries(x);localStorage.setItem("dn-manual-v4",JSON.stringify(x))};
 const saveSnaps=(x)=>{setSnapshots(x);localStorage.setItem("dn-snapshots-v43",JSON.stringify(x))};
 const saveMargeSnaps=(x)=>{setMargeSnapshots(x);localStorage.setItem("marge-snapshots-v1",JSON.stringify(x))};
 function submit(e){e.preventDefault();const numeric=["views","likes","comments","shares","retention","completion","scrollStop","followers"];const entry={...form,id:crypto.randomUUID()};numeric.forEach(k=>entry[k]=form[k]===""?null:Number(form[k]));save([entry,...entries]);setForm(freshForm())}
 function submitSnap(e){e.preventDefault();const numeric=["hours","views","likes","comments","shares","scrollStop","retention","completion","avgViewDuration","followers","shownInFeed"];const entry={...snap,id:crypto.randomUUID(),capturedAt:new Date().toISOString()};numeric.forEach(k=>entry[k]=snap[k]===""?null:Number(snap[k]));if(snap.project==="MARGE."){saveMargeSnaps([entry,...margeSnapshots])}else{saveSnaps([entry,...snapshots])}setSnap({...freshSnap(),project:snap.project,dossier:snap.dossier,platform:snap.platform})}
 return <main className="standalone"><a className="back-link" href="/">← Retour au Control Center</a><header><p className="eyebrow">DOSSIER NOIR · V4.3</p><h1>Centre de données</h1><p>Ajoute les chiffres finaux et surtout les checkpoints H+ du dernier dossier. L'assistant utilisera toute la trajectoire pour ses analyses.</p></header>
 <section className="panel checkpoint-panel"><div className="panel-heading"><div><p>SUIVI TEMPOREL</p><h2>Ajouter un checkpoint H+</h2></div></div><div className="checkpoint-help"><b>À relever idéalement :</b> H+1 · H+3 · H+6 · H+12 · H+24 · H+48. YouTube : vues, « ont continué », rétention, durée moyenne, likes/commentaires, abonnés et affichages dans le flux.</div>
 <form className="admin-form" onSubmit={submitSnap}>
 <label>Projet<select value={snap.project} onChange={e=>setSnap({...snap,project:e.target.value,dossier:e.target.value==="MARGE."?"001":"005"})}><option>Dossier Noir</option><option>MARGE.</option></select></label>
 <label>{snap.project==="MARGE."?"Vidéo MARGE.":"Dossier"}<input value={snap.dossier} onChange={e=>setSnap({...snap,dossier:e.target.value})}/></label>
 <label>Checkpoint<select value={snap.hours} onChange={e=>setSnap({...snap,hours:e.target.value})}>{checkpoints.map(h=><option key={h} value={h}>H+{h}{h==="168"?" (7 jours)":""}</option>)}</select></label>
 <label>Plateforme<select value={snap.platform} onChange={e=>setSnap({...snap,platform:e.target.value})}><option>YouTube Shorts</option><option>TikTok</option><option>Instagram Reels</option></select></label>
 {[["views","Vues"],["scrollStop","Ont continué à regarder (%)"],["retention","Rétention moyenne (%)"],["avgViewDuration","Durée moyenne vue (secondes)"],["completion","Complétion (%)"],["likes","Likes"],["comments","Commentaires"],["shares","Partages"],["followers","Abonnés gagnés"],["shownInFeed","Affichages dans le flux"]].map(([n,l])=><label key={n}>{l}<input type="number" step="0.1" value={snap[n]} onChange={e=>setSnap({...snap,[n]:e.target.value})}/></label>)}
 <button className="primary" type="submit">Enregistrer le checkpoint</button></form></section>
 <section className="panel admin-list"><div className="panel-heading"><div><p>HISTORIQUE</p><h2>Checkpoints H+ · Dossier Noir & MARGE.</h2></div></div>{snapshots.length===0&&margeSnapshots.length===0?<div className="empty-state compact">Aucun checkpoint enregistré</div>:<>{snapshots.sort((a,b)=>Number(b.hours)-Number(a.hours)).map(x=><div className="admin-row" key={x.id}><span><b>D{x.dossier} · H+{x.hours}</b> · {x.platform} · {x.views} vues · Hook {x.scrollStop??"—"}% · Rétention {x.retention??"—"}%</span><button onClick={()=>saveSnaps(snapshots.filter(i=>i.id!==x.id))}>Supprimer</button></div>)}{margeSnapshots.sort((a,b)=>Number(b.hours)-Number(a.hours)).map(x=><div className="admin-row marge-admin-row" key={x.id}><span><b>M{x.dossier} · H+{x.hours}</b> · {x.platform} · {x.views} vues · Hook {x.scrollStop??"—"}% · Rétention {x.retention??"—"}%</span><button onClick={()=>saveMargeSnaps(margeSnapshots.filter(i=>i.id!==x.id))}>Supprimer</button></div>)}</>}</section>
 <section className="panel"><div className="panel-heading"><div><p>RÉSULTAT GLOBAL</p><h2>Ajouter des statistiques finales</h2></div></div><form className="admin-form" onSubmit={submit}>
 {[["dossier","Dossier","text"],["title","Titre","text"],["hook","Hook exact","text"],["views","Vues","number"],["likes","Likes","number"],["comments","Commentaires","number"],["shares","Partages","number"],["scrollStop","Ont continué à regarder (%)","number"],["retention","Rétention moyenne (%)","number"],["completion","Complétion (%)","number"],["followers","Abonnés gagnés","number"]].map(([n,l,t])=><label key={n}>{l}<input type={t} step={t==="number"?"0.1":undefined} value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})}/></label>)}
 <label>Plateforme<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option>TikTok</option><option>YouTube Shorts</option><option>Instagram Reels</option></select></label><label>Date et heure<input type="datetime-local" value={form.publishedAt} onChange={e=>setForm({...form,publishedAt:e.target.value})}/></label><button className="primary">Enregistrer les statistiques finales</button></form></section>
 </main>
}