'use client';
import { useEffect,useMemo,useState } from "react";
import { Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { bestHour,diagnosticFor,engagementRate,estimateRevenue,groupByDossier,nextTargets,normalizeDossier,applyEditorialMetrics,viralScore } from "../lib/analytics";
import { demoVideos } from "../lib/demo";

const fmt=(v)=>new Intl.NumberFormat("fr-FR",{notation:Number(v)>999999?"compact":"standard",maximumFractionDigits:1}).format(Number(v||0));
const pct=(v)=>v===null||v===undefined||v===""?"—":Number(v).toFixed(1)+" %";
function Badge({children,tone=""}){return <span className={`badge ${tone}`}>{children}</span>}
function Ring({value}){return <div className="score-ring" style={{"--score-angle":`${value*3.6}deg`}}><span>{value}</span><small>/100</small></div>}
function Kpi({label,value,detail,accent}){return <article className={`kpi ${accent?"accent":""}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>}
function Platform({name}){const tone=name.includes("YouTube")?"youtube":name.includes("TikTok")?"tiktok":"instagram";return <Badge tone={tone}>{name}</Badge>}

export default function Dashboard(){
 const [project,setProject]=useState("dossier"); const [view,setView]=useState("dashboard"); const [youtube,setYoutube]=useState({status:"loading",videos:[],message:""}); const [manual,setManual]=useState([]); const [snapshots,setSnapshots]=useState([]); const [demoMode,setDemoMode]=useState(true); const [analysis,setAnalysis]=useState(""); const [analyzing,setAnalyzing]=useState(false); const [compareA,setCompareA]=useState("003"); const [compareB,setCompareB]=useState("004");
 useEffect(()=>{fetch("/api/youtube").then(r=>r.json()).then(setYoutube).catch(()=>setYoutube({status:"error",videos:[],message:"Connexion YouTube impossible."})); try{setManual(JSON.parse(localStorage.getItem("dn-manual-v4")||localStorage.getItem("dn-manual-v3")||"[]"));setSnapshots(JSON.parse(localStorage.getItem("dn-snapshots-v43")||"[]"))}catch{setManual([]);setSnapshots([])}},[]);
 const real=useMemo(()=>[...(youtube.videos||[]),...manual],[youtube.videos,manual]); const videos=demoMode&&!real.length?demoVideos:real;
 const median=useMemo(()=>{const a=videos.map(v=>Number(v.views||0)).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:1},[videos]);
 const enriched=useMemo(()=>videos.map(v=>{const base=applyEditorialMetrics(v);return {...base,engagement:engagementRate(base),score:viralScore(base,median),revenue:estimateRevenue(base)}}),[videos,median]);
 const dossiers=useMemo(()=>groupByDossier(enriched),[enriched]); const latest=dossiers[dossiers.length-1]; const diagnosis=diagnosticFor(latest); const targets=nextTargets(dossiers);
 const totals=useMemo(()=>enriched.reduce((a,v)=>({views:a.views+Number(v.views||0),interactions:a.interactions+Number(v.likes||0)+Number(v.comments||0)+Number(v.shares||0),followers:a.followers+Number(v.followers||0)}),{views:0,interactions:0,followers:0}),[enriched]);
 const ranked=[...dossiers].sort((a,b)=>b.score-a.score); const best=ranked[0]; const hour=bestHour(enriched);
 const trend=dossiers.map(d=>({label:`D${d.dossier}`,views:d.views,retention:d.retention==null?null:Number(d.retention.toFixed(1)),hook:d.scrollStop==null?null:Number(d.scrollStop.toFixed(1))}));
 async function runAnalysis(){setAnalyzing(true);try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos:enriched,dossiers,targets,snapshots:snapshots.filter(x=>x.dossier===latest?.dossier)})});const p=await r.json();setAnalysis(p.analysis||"Analyse indisponible.")}finally{setAnalyzing(false)}}

 const latestSnaps=useMemo(()=>snapshots.filter(x=>x.dossier===latest?.dossier).sort((a,b)=>Number(a.hours)-Number(b.hours)),[snapshots,latest?.dossier]);
 const velocityData=useMemo(()=>latestSnaps.map((x,i)=>{const prev=latestSnaps[i-1];const dh=prev?Math.max(Number(x.hours)-Number(prev.hours),1):Math.max(Number(x.hours),1);const dv=prev?Number(x.views||0)-Number(prev.views||0):Number(x.views||0);return {...x,label:`H+${x.hours}`,velocity:Math.round(dv/dh)}}),[latestSnaps]);
 const potential=useMemo(()=>{if(velocityData.length<2)return {label:"À MESURER",tone:"warning",detail:"Ajoute au moins deux checkpoints H+."};const a=velocityData[velocityData.length-1],b=velocityData[velocityData.length-2];if(a.velocity>b.velocity*1.25)return {label:"FORTE ACCÉLÉRATION",tone:"success",detail:`${a.velocity} vues/h sur la dernière fenêtre.`};if(a.velocity>=b.velocity*.85)return {label:"PROMETTEUR",tone:"success",detail:`Diffusion stable à ${a.velocity} vues/h.`};if(a.velocity>=b.velocity*.5)return {label:"NORMAL",tone:"warning",detail:`La diffusion ralentit à ${a.velocity} vues/h.`};return {label:"RALENTISSEMENT",tone:"danger",detail:`La poussée retombe à ${a.velocity} vues/h.`}},[velocityData]);
 const compareDossier=(id)=>dossiers.find(d=>d.dossier===id);
 const ca=compareDossier(compareA),cb=compareDossier(compareB);
 const snapAt=(id,h)=>snapshots.find(x=>x.dossier===id&&Number(x.hours)===h);
 const snapshotViews=(id,h)=>{const x=snapAt(id,h);return x&&x.views!==null&&x.views!==undefined?fmt(x.views):"—"};
 const snapshotDelta=(aId,bId,h)=>{const a=snapAt(aId,h),b=snapAt(bId,h);if(!a||!b||a.views===null||a.views===undefined||b.views===null||b.views===undefined)return "—";const av=Number(a.views),bv=Number(b.views);const d=(bv-av)/Math.max(av,1)*100;return `${d>=0?"+":""}${d.toFixed(0)}%`};
 const deltaMetric=(a,b,key)=>{const av=Number(a?.[key]);const bv=Number(b?.[key]);if(!Number.isFinite(av)||!Number.isFinite(bv)||a?.[key]==null||b?.[key]==null)return "—";const d=bv-av;return `${d>=0?"+":""}${d.toFixed(1)}`};
 const titles={dashboard:"Control Center",dossiers:"Comparaison des dossiers",videos:"Données par plateforme",ai:"Analyse stratégique",hooks:"Laboratoire des hooks",alerts:"Objectifs & alertes"};

 return <div className={`application project-${project}`}><aside className="sidebar"><a className="brand" href="/"><span>{project==="marge"?"M.":project==="vs"?"VS":"DN"}</span><div><b>{project==="marge"?<>MARGE<em>.</em></>:project==="vs"?<>CONTENT <em>LAB</em></>:<>DOSSIER <em>NOIR</em></>}</b><small>CONTENT LAB V5.0</small></div></a>
 <div className="project-switcher"><button className={project==="dossier"?"active dossier-tab":"dossier-tab"} onClick={()=>{setProject("dossier");setView("dashboard")}}>DOSSIER NOIR</button><button className={project==="marge"?"active marge-tab":"marge-tab"} onClick={()=>setProject("marge")}>MARGE.</button><button className={project==="vs"?"active vs-tab":"vs-tab"} onClick={()=>setProject("vs")}>VS</button></div>
 {project==="dossier"&&<nav>{[["dashboard","Vue d'ensemble","◫"],["dossiers","Dossiers","▥"],["videos","Plateformes","▶"],["ai","Analyse IA","✦"],["hooks","Hooks","⌁"],["alerts","Objectifs","!"]].map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span>{icon}</span>{label}</button>)}</nav>}
 {project==="marge"&&<nav className="marge-nav"><button className="active"><span>◫</span>Vue d'ensemble</button><button><span>▶</span>MARGE 001</button><button><span>⌁</span>Hooks</button><button><span>!</span>Objectifs</button></nav>}
 {project==="vs"&&<nav className="vs-nav"><button className="active"><span>⇄</span>Comparatif</button><button><span>✦</span>Insights HOOKLY</button></nav>}
 <div className="sidebar-footer"><label className="demo-toggle"><input type="checkbox" checked={demoMode} onChange={e=>setDemoMode(e.target.checked)}/><span/>Mode démo</label><a href="/admin">Ajouter des statistiques</a></div></aside>
 <main className="content"><header className="topbar"><div><p className="eyebrow">{project==="marge"?"MARGE. · PERFORMANCE LAB V5.0":project==="vs"?"DOSSIER NOIR × MARGE. · CROSS LAB":"DOSSIER NOIR · ANALYTICS V5.0"}</p><h1>{project==="marge"?"MARGE. Control Center":project==="vs"?"Dossier Noir VS MARGE.":titles[view]}</h1></div><div className="top-status">{project==="dossier"?<><Badge tone={youtube.status==="ok"?"success":"warning"}>{youtube.status==="ok"?"YouTube connecté":"YouTube en attente"}</Badge><span className="sync-status"><i/>Synchronisation horaire</span></>:<Badge tone={project==="marge"?"marge":"warning"}>{project==="marge"?"DATASET M001":"CROSS-PROJECT"}</Badge>}</div></header>
 {project==="dossier"&&view==="dashboard"&&<><section className="kpi-grid"><Kpi label="Vues cumulées" value={fmt(totals.views)} detail={`${dossiers.length} dossiers analysés`}/><Kpi label="Meilleure rétention" value={best?pct(Math.max(0,...dossiers.map(d=>Number(d.retention||0)))):"—"} detail="Qualité du montage après le hook"/><Kpi label="Meilleur arrêt du scroll" value={best?pct(Math.max(0,...dossiers.map(d=>Number(d.scrollStop||0)))):"—"} detail="Ont continué à regarder"/><Kpi label={`Objectif Dossier ${targets.dossier}`} value={fmt(targets.views)} detail="Objectif de vues recommandé" accent/></section>
 <section className="main-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p>PROGRESSION</p><h2>Vues par dossier</h2></div><Badge tone="success">DOSSIER PAR DOSSIER</Badge></div><div className="chart-container"><ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="viewsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e53935" stopOpacity={.5}/><stop offset="100%" stopColor="#e53935" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#282828" vertical={false}/><XAxis dataKey="label" stroke="#777" axisLine={false} tickLine={false}/><YAxis stroke="#777" axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#111",border:"1px solid #333"}}/><Area type="monotone" dataKey="views" stroke="#e53935" strokeWidth={3} fill="url(#viewsFill)"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel top-video"><div className="panel-heading"><div><p>MEILLEURE PERFORMANCE</p><h2>Dossier référence</h2></div></div>{best?<><Ring value={best.score}/><h3>Dossier {best.dossier}</h3><p>{best.title}</p><div className="inline-stats"><span>{fmt(best.views)} vues</span><span>{pct(best.retention)} rétention</span></div></>:<div className="empty-state">Aucune donnée</div>}</article></section>
 <section className="focus-grid"><article className="panel diagnosis"><div className="panel-heading"><div><p>DIAGNOSTIC DU DERNIER DOSSIER</p><h2>Dossier {latest?.dossier||"—"}</h2></div><Badge tone={diagnosis.tone}>{diagnosis.label}</Badge></div><p className="diagnosis-text">{diagnosis.message}</p><div className="metric-bars"><div><span>Hook</span><b>{pct(latest?.scrollStop)}</b><progress max="100" value={latest?.scrollStop||0}/></div><div><span>Rétention</span><b>{pct(latest?.retention)}</b><progress max="100" value={latest?.retention||0}/></div><div><span>Complétion</span><b>{pct(latest?.completion)}</b><progress max="100" value={latest?.completion||0}/></div></div></article>
 <article className="panel target-card"><div className="panel-heading"><div><p>PROCHAIN OBJECTIF</p><h2>Dossier {targets.dossier}</h2></div></div><div className="target-list"><div><span>Arrêt du scroll</span><strong>≥ {targets.scrollStop}%</strong></div><div><span>Rétention</span><strong>≥ {targets.retention}%</strong></div><div><span>Complétion</span><strong>≥ {targets.completion}%</strong></div><div><span>Vues</span><strong>≥ {fmt(targets.views)}</strong></div></div></article></section>
 <section className="performance-lab">
  <article className="panel performance-chart"><div className="panel-heading"><div><p>H+ PERFORMANCE</p><h2>Vitesse de diffusion · Dossier {latest?.dossier||"—"}</h2></div><Badge tone={potential.tone}>{potential.label}</Badge></div>
   {velocityData.length?<div className="chart-container"><ResponsiveContainer><AreaChart data={velocityData}><CartesianGrid stroke="#282828" vertical={false}/><XAxis dataKey="label" stroke="#777" axisLine={false} tickLine={false}/><YAxis stroke="#777" axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#111",border:"1px solid #333"}}/><Area type="monotone" dataKey="views" stroke="#e53935" strokeWidth={3} fillOpacity={.12} fill="#e53935"/><Area type="monotone" dataKey="velocity" stroke="#aaa" strokeWidth={2} fillOpacity={0}/></AreaChart></ResponsiveContainer></div>:<div className="empty-state compact">Ajoute les checkpoints H+ du dernier dossier pour afficher sa trajectoire.</div>}
   <p className="potential-detail">{potential.detail}</p>
  </article>
  <article className="panel verdict-board"><div className="panel-heading"><div><p>VERDICT EXPRESS</p><h2>Dossier {latest?.dossier||"—"}</h2></div></div>
   <div className="verdict-row"><span>HOOK</span><Badge tone={Number(latest?.scrollStop)>=50?"success":"danger"}>{latest?.scrollStop==null?"INCONNU":Number(latest.scrollStop)>=50?"SOLIDE":"À TRAVAILLER"}</Badge></div>
   <div className="verdict-row"><span>MONTAGE</span><Badge tone={Number(latest?.retention)>=85?"success":"warning"}>{latest?.retention==null?"INCONNU":Number(latest.retention)>=85?"EXCELLENT":"À OPTIMISER"}</Badge></div>
   <div className="verdict-row"><span>DIFFUSION</span><Badge tone={potential.tone}>{potential.label}</Badge></div>
   <div className="priority-box"><small>PRIORITÉ D{targets.dossier}</small><strong>{Number(latest?.scrollStop)<50?"HOOK":Number(latest?.retention)<85?"MONTAGE":"AMPLIFIER CE QUI MARCHE"}</strong></div>
  </article>
 </section></>}
 {project==="dossier"&&view==="dossiers"&&<section className="panel"><div className="panel-heading"><div><p>ÉVOLUTION</p><h2>001 → {latest?.dossier||"—"}</h2></div></div><div className="dossier-grid">{dossiers.map((d,i)=>{const prev=dossiers[i-1];const delta=prev?((d.views-prev.views)/Math.max(prev.views,1))*100:null;return <article className="dossier-card" key={d.dossier}><div><Badge tone={i===dossiers.length-1?"danger":""}>DOSSIER {d.dossier}</Badge><Ring value={d.score}/></div><h3>{d.title}</h3><p>“{d.hook}”</p><dl><div><dt>Vues</dt><dd>{fmt(d.views)} {delta!==null&&<small className={delta>=0?"up":"down"}>{delta>=0?"+":""}{delta.toFixed(0)}%</small>}</dd></div><div><dt>Hook</dt><dd>{pct(d.scrollStop)}</dd></div><div><dt>Rétention</dt><dd>{pct(d.retention)}</dd></div><div><dt>Complétion</dt><dd>{pct(d.completion)}</dd></div></dl></article>})}</div>
 <div className="comparator"><div className="panel-heading"><div><p>DUEL DIRECT</p><h2>Comparer deux dossiers</h2></div></div>
 <div className="compare-selects"><select value={compareA} onChange={e=>setCompareA(e.target.value)}>{dossiers.map(d=><option key={d.dossier} value={d.dossier}>Dossier {d.dossier}</option>)}</select><b>VS</b><select value={compareB} onChange={e=>setCompareB(e.target.value)}>{dossiers.map(d=><option key={d.dossier} value={d.dossier}>Dossier {d.dossier}</option>)}</select></div>
 <div className="compare-table">
 {[
 ["Vues finales",ca?.views,cb?.views,ca&&cb?`${((cb.views-ca.views)/Math.max(ca.views,1)*100)>=0?"+":""}${((cb.views-ca.views)/Math.max(ca.views,1)*100).toFixed(0)}%`:"—"],
 ["Hook",pct(ca?.scrollStop),pct(cb?.scrollStop),deltaMetric(ca,cb,"scrollStop")+" pts"],
 ["Rétention",pct(ca?.retention),pct(cb?.retention),deltaMetric(ca,cb,"retention")+" pts"],
 ["H+1 vues",snapshotViews(compareA,1),snapshotViews(compareB,1),snapshotDelta(compareA,compareB,1)],
 ["H+6 vues",snapshotViews(compareA,6),snapshotViews(compareB,6),snapshotDelta(compareA,compareB,6)],
 ["H+24 vues",snapshotViews(compareA,24),snapshotViews(compareB,24),snapshotDelta(compareA,compareB,24)]
 ].map(([label,a,b,d])=><div className="compare-row" key={label}><span>{label}</span><b>{a}</b><b>{b}</b><strong>{d}</strong></div>)}
 </div></div></section>}
 {project==="dossier"&&view==="videos"&&<section className="panel"><div className="panel-heading"><div><p>DONNÉES BRUTES</p><h2>Résultats par plateforme</h2></div></div><div className="table-wrapper"><table><thead><tr><th>Dossier</th><th>Plateforme</th><th>Vues</th><th>Hook</th><th>Rétention</th><th>Complétion</th><th>Engagement</th><th>Score</th></tr></thead><tbody>{enriched.map(v=><tr key={`${v.platform}-${v.id}`}><td><b>N°{v.dossier}</b><span>{v.title}</span></td><td><Platform name={v.platform}/></td><td>{fmt(v.views)}</td><td>{pct(v.scrollStop)}</td><td>{pct(v.retention)}</td><td>{pct(v.completion)}</td><td>{pct(v.engagement)}</td><td><strong className={v.score>=70?"hot":""}>{v.score}/100</strong></td></tr>)}</tbody></table></div></section>}
 {project==="dossier"&&view==="ai"&&<><section className="strategy-grid">
<article className="strategy-card"><span>HOOK</span><strong>{pct(latest?.scrollStop)}</strong><Badge tone={Number(latest?.scrollStop)>=50?"success":"danger"}>{Number(latest?.scrollStop)>=50?"SOLIDE":"PRIORITÉ N°1"}</Badge><p>Capacité à arrêter le scroll.</p></article>
<article className="strategy-card"><span>MONTAGE</span><strong>{pct(latest?.retention)}</strong><Badge tone={Number(latest?.retention)>=85?"success":"warning"}>{Number(latest?.retention)>=85?"EXCELLENT":"À OPTIMISER"}</Badge><p>Rétention après l'ouverture.</p></article>
<article className="strategy-card"><span>DIFFUSION</span><strong>{fmt(latest?.views)}</strong><Badge tone="warning">VUES</Badge><p>Performance observée du dossier.</p></article>
<article className="strategy-card mission"><span>MISSION D{targets.dossier}</span><strong>≥ {targets.scrollStop}%</strong><Badge tone="danger">HOOK</Badge><p>Sans descendre sous {targets.retention}% de rétention.</p></article>
</section>
<section className="two-column"><article className="panel"><div className="panel-heading"><div><p>ASSISTANT STRATÉGIQUE</p><h2>Verdict Dossier {latest?.dossier}</h2></div></div><button className="primary" onClick={runAnalysis} disabled={analyzing}>{analyzing?"Analyse en cours...":"Analyser toutes les données"}</button><div className="analysis-box">{analysis||`Lecture automatique actuelle : ${diagnosis.message}\n\nAjoute les relevés H+1, H+3, H+6, H+12, H+24 et H+48 pour analyser aussi la trajectoire de diffusion.`}</div></article>
<article className="panel"><div className="panel-heading"><div><p>TRAJECTOIRE DU DERNIER DOSSIER</p><h2>Checkpoints enregistrés</h2></div><Badge tone="success">{snapshots.filter(x=>x.dossier===latest?.dossier).length} relevés</Badge></div>
<div className="snapshot-mini">{snapshots.filter(x=>x.dossier===latest?.dossier).sort((a,b)=>Number(a.hours)-Number(b.hours)).map(x=><div key={x.id}><b>H+{x.hours}</b><span>{fmt(x.views)} vues</span><span>{pct(x.scrollStop)} hook</span><span>{pct(x.retention)} rétention</span></div>)}</div>
<a className="snapshot-link" href="/admin">+ Ajouter un checkpoint H+</a></article></section></>}
 {project==="dossier"&&view==="hooks"&&<section className="panel"><div className="panel-heading"><div><p>HOOK LAB</p><h2>Classement par arrêt du scroll</h2></div></div><div className="hook-list">{[...dossiers].sort((a,b)=>Number(b.scrollStop||0)-Number(a.scrollStop||0)).map((d,i)=><article key={d.dossier}><b>#{i+1}</b><div><h3>“{d.hook||d.title}”</h3><p>Dossier {d.dossier} · {fmt(d.views)} vues · {pct(d.retention)} de rétention après le hook</p></div><div className="hook-score"><strong>{pct(d.scrollStop)}</strong><small>ont continué</small></div></article>)}</div></section>}
 {project==="dossier"&&view==="alerts"&&<section className="two-column"><article className="panel"><div className="panel-heading"><div><p>SEUILS V4</p><h2>Règles de performance</h2></div></div>{[["Hook",latest?.scrollStop,50],["Rétention",latest?.retention,80],["Complétion",latest?.completion,60]].map(([label,value,goal])=><div className="rule" key={label}><span>{label} · {pct(value)} / objectif {goal}%</span><Badge tone={Number(value)>=goal?"success":"danger"}>{Number(value)>=goal?"VALIDÉ":"À TRAVAILLER"}</Badge></div>)}<p className="muted">Les seuils servent à décider quoi modifier sans casser les éléments qui fonctionnent déjà.</p></article><article className="panel target-card"><div className="panel-heading"><div><p>MISSION</p><h2>Dossier {targets.dossier}</h2></div></div><div className="large-alert"><span>🎯</span><h3>Faire passer le hook au-dessus de {targets.scrollStop}%</h3><p>Conserver une rétention d'au moins {targets.retention}%.</p></div></article></section>}
 {project==="marge"&&<><section className="marge-hero panel"><div><p className="marge-kicker">MARGE. · TOUT SE JOUE DANS LA MARGE.</p><h2>MARGE 001</h2><p>Premier point de référence du média business. Les performances seront alimentées aux checkpoints H+1, H+2, H+4 et H+24.</p></div><div className="marge-status-orb"><span>001</span><small>BASELINE</small></div></section>
 <section className="kpi-grid marge-kpis"><Kpi label="Vues" value="—" detail="En attente du premier relevé"/><Kpi label="Arrêt du scroll" value="—" detail="Hook MARGE 001"/><Kpi label="Rétention" value="—" detail="Durée moyenne / vidéo"/><Kpi label="Objectif de test" value="10K" detail="Potentiel à valider" accent/></section>
 <section className="marge-grid"><article className="panel"><div className="panel-heading"><div><p>IDENTITÉ MARGE.</p><h2>Baseline créative</h2></div><Badge tone="marge">VERROUILLÉE</Badge></div><div className="marge-specs"><div><span>Positionnement</span><strong>Business · Marge · Monétisation</strong></div><div><span>Signature</span><strong>Tout se joue dans la marge.</strong></div><div><span>Voix</span><strong>Viraj</strong></div><div><span>Format</span><strong>9:16 · ~30 s</strong></div></div></article>
 <article className="panel"><div className="panel-heading"><div><p>CHECKPOINTS</p><h2>Dataset M001</h2></div><Badge tone="warning">À REMPLIR</Badge></div><div className="marge-checkpoints">{[1,2,4,24].map(h=><div key={h}><b>H+{h}</b><span>Vues —</span><span>Hook —</span><span>Rétention —</span></div>)}</div></article></section>
 <section className="panel marge-objective"><div className="panel-heading"><div><p>PROCHAINE DÉCISION</p><h2>MARGE 002</h2></div></div><p>La structure de MARGE 002 sera décidée après lecture du checkpoint H+4 de MARGE 001 : hook, durée, complétion et vitesse de diffusion.</p></section></>}
 {project==="vs"&&<><section className="vs-hero"><article className="vs-side dossier-side"><span>DOSSIER NOIR</span><strong>{fmt(totals.views)}</strong><small>vues cumulées mesurées</small></article><div className="vs-center"><b>VS</b><span>HOOKLY CROSS-LAB</span></div><article className="vs-side marge-side"><span>MARGE.</span><strong>—</strong><small>baseline en attente</small></article></section>
 <section className="vs-grid"><article className="panel"><div className="panel-heading"><div><p>COMPARAISON</p><h2>Ce qu'on mesure</h2></div></div><div className="vs-metrics"><div><span>Scroll-stop</span><b>{best?pct(Math.max(0,...dossiers.map(d=>Number(d.scrollStop||0)))):"—"}</b><strong>—</strong></div><div><span>Rétention</span><b>{best?pct(Math.max(0,...dossiers.map(d=>Number(d.retention||0)))):"—"}</b><strong>—</strong></div><div><span>Meilleure vidéo</span><b>{best?`D${best.dossier}`:"—"}</b><strong>M001</strong></div><div><span>Dataset</span><b>{dossiers.length} dossiers</b><strong>1 baseline</strong></div></div></article>
 <article className="panel hookly-panel"><div className="panel-heading"><div><p>HOOKLY</p><h2>Cross-project learning</h2></div><Badge tone="marge">DATA → ACTION</Badge></div><p>Le VS ne cherche pas à déclarer un “gagnant”. Il compare les mécaniques de hook, de rétention et de distribution pour trouver ce qui se transfère d'un média à l'autre.</p><div className="hookly-flow"><span>DATA</span><i>→</i><span>DIAGNOSTIC</span><i>→</i><span>ACTION</span><i>→</i><span>NOUVELLE VIDÉO</span></div></article></section></>}
 {!demoMode&&youtube.message&&<div className="system-message">{youtube.message}</div>}</main></div>
}
