'use client';
import { useEffect,useMemo,useState } from "react";
import { Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { bestHour,diagnosticFor,engagementRate,estimateRevenue,groupByDossier,nextTargets,normalizeDossier,viralScore } from "../lib/analytics";
import { demoVideos } from "../lib/demo";

const fmt=(v)=>new Intl.NumberFormat("fr-FR",{notation:Number(v)>999999?"compact":"standard",maximumFractionDigits:1}).format(Number(v||0));
const pct=(v)=>v===null||v===undefined||v===""?"—":Number(v).toFixed(1)+" %";
function Badge({children,tone=""}){return <span className={`badge ${tone}`}>{children}</span>}
function Ring({value}){return <div className="score-ring" style={{"--score-angle":`${value*3.6}deg`}}><span>{value}</span><small>/100</small></div>}
function Kpi({label,value,detail,accent}){return <article className={`kpi ${accent?"accent":""}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>}
function Platform({name}){const tone=name.includes("YouTube")?"youtube":name.includes("TikTok")?"tiktok":"instagram";return <Badge tone={tone}>{name}</Badge>}

export default function Dashboard(){
 const [view,setView]=useState("dashboard"); const [youtube,setYoutube]=useState({status:"loading",videos:[],message:""}); const [manual,setManual]=useState([]); const [snapshots,setSnapshots]=useState([]); const [demoMode,setDemoMode]=useState(true); const [analysis,setAnalysis]=useState(""); const [analyzing,setAnalyzing]=useState(false);
 useEffect(()=>{fetch("/api/youtube").then(r=>r.json()).then(setYoutube).catch(()=>setYoutube({status:"error",videos:[],message:"Connexion YouTube impossible."})); try{setManual(JSON.parse(localStorage.getItem("dn-manual-v4")||localStorage.getItem("dn-manual-v3")||"[]"));setSnapshots(JSON.parse(localStorage.getItem("dn-snapshots-v43")||"[]"))}catch{setManual([]);setSnapshots([])}},[]);
 const real=useMemo(()=>[...(youtube.videos||[]),...manual],[youtube.videos,manual]); const videos=demoMode&&!real.length?demoVideos:real;
 const median=useMemo(()=>{const a=videos.map(v=>Number(v.views||0)).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:1},[videos]);
 const enriched=useMemo(()=>videos.map(v=>({...v,dossier:normalizeDossier(v),engagement:engagementRate(v),score:viralScore(v,median),revenue:estimateRevenue(v)})),[videos,median]);
 const dossiers=useMemo(()=>groupByDossier(enriched),[enriched]); const latest=dossiers[dossiers.length-1]; const diagnosis=diagnosticFor(latest); const targets=nextTargets(dossiers);
 const totals=useMemo(()=>enriched.reduce((a,v)=>({views:a.views+Number(v.views||0),interactions:a.interactions+Number(v.likes||0)+Number(v.comments||0)+Number(v.shares||0),followers:a.followers+Number(v.followers||0)}),{views:0,interactions:0,followers:0}),[enriched]);
 const ranked=[...dossiers].sort((a,b)=>b.score-a.score); const best=ranked[0]; const hour=bestHour(enriched);
 const trend=dossiers.map(d=>({label:`D${d.dossier}`,views:d.views,retention:d.retention==null?null:Number(d.retention.toFixed(1)),hook:d.scrollStop==null?null:Number(d.scrollStop.toFixed(1))}));
 async function runAnalysis(){setAnalyzing(true);try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos:enriched,dossiers,targets,snapshots:snapshots.filter(x=>x.dossier===latest?.dossier)})});const p=await r.json();setAnalysis(p.analysis||"Analyse indisponible.")}finally{setAnalyzing(false)}}
 const titles={dashboard:"Control Center",dossiers:"Comparaison des dossiers",videos:"Données par plateforme",ai:"Analyse stratégique",hooks:"Laboratoire des hooks",alerts:"Objectifs & alertes"};
 return <div className="application"><aside className="sidebar"><a className="brand" href="/"><span>DN</span><div><b>DOSSIER <em>NOIR</em></b><small>CONTROL CENTER V4.3</small></div></a><nav>{[["dashboard","Vue d'ensemble","◫"],["dossiers","Dossiers","▥"],["videos","Plateformes","▶"],["ai","Analyse IA","✦"],["hooks","Hooks","⌁"],["alerts","Objectifs","!"]].map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><label className="demo-toggle"><input type="checkbox" checked={demoMode} onChange={e=>setDemoMode(e.target.checked)}/><span/>Mode démo</label><a href="/admin">Ajouter des statistiques</a></div></aside>
 <main className="content"><header className="topbar"><div><p className="eyebrow">DOSSIER NOIR · ANALYTICS V4.3</p><h1>{titles[view]}</h1></div><div className="top-status"><Badge tone={youtube.status==="ok"?"success":"warning"}>{youtube.status==="ok"?"YouTube connecté":"YouTube en attente"}</Badge><span className="sync-status"><i/>Synchronisation horaire</span></div></header>
 {view==="dashboard"&&<><section className="kpi-grid"><Kpi label="Vues cumulées" value={fmt(totals.views)} detail={`${dossiers.length} dossiers analysés`}/><Kpi label="Meilleure rétention" value={best?pct(Math.max(0,...dossiers.map(d=>Number(d.retention||0)))):"—"} detail="Qualité du montage après le hook"/><Kpi label="Meilleur arrêt du scroll" value={best?pct(Math.max(0,...dossiers.map(d=>Number(d.scrollStop||0)))):"—"} detail="Ont continué à regarder"/><Kpi label={`Objectif Dossier ${targets.dossier}`} value={fmt(targets.views)} detail="Objectif de vues recommandé" accent/></section>
 <section className="main-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p>PROGRESSION</p><h2>Vues par dossier</h2></div><Badge tone="success">DOSSIER PAR DOSSIER</Badge></div><div className="chart-container"><ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="viewsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e53935" stopOpacity={.5}/><stop offset="100%" stopColor="#e53935" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#282828" vertical={false}/><XAxis dataKey="label" stroke="#777" axisLine={false} tickLine={false}/><YAxis stroke="#777" axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#111",border:"1px solid #333"}}/><Area type="monotone" dataKey="views" stroke="#e53935" strokeWidth={3} fill="url(#viewsFill)"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel top-video"><div className="panel-heading"><div><p>MEILLEURE PERFORMANCE</p><h2>Dossier référence</h2></div></div>{best?<><Ring value={best.score}/><h3>Dossier {best.dossier}</h3><p>{best.title}</p><div className="inline-stats"><span>{fmt(best.views)} vues</span><span>{pct(best.retention)} rétention</span></div></>:<div className="empty-state">Aucune donnée</div>}</article></section>
 <section className="focus-grid"><article className="panel diagnosis"><div className="panel-heading"><div><p>DIAGNOSTIC DU DERNIER DOSSIER</p><h2>Dossier {latest?.dossier||"—"}</h2></div><Badge tone={diagnosis.tone}>{diagnosis.label}</Badge></div><p className="diagnosis-text">{diagnosis.message}</p><div className="metric-bars"><div><span>Hook</span><b>{pct(latest?.scrollStop)}</b><progress max="100" value={latest?.scrollStop||0}/></div><div><span>Rétention</span><b>{pct(latest?.retention)}</b><progress max="100" value={latest?.retention||0}/></div><div><span>Complétion</span><b>{pct(latest?.completion)}</b><progress max="100" value={latest?.completion||0}/></div></div></article>
 <article className="panel target-card"><div className="panel-heading"><div><p>PROCHAIN OBJECTIF</p><h2>Dossier {targets.dossier}</h2></div></div><div className="target-list"><div><span>Arrêt du scroll</span><strong>≥ {targets.scrollStop}%</strong></div><div><span>Rétention</span><strong>≥ {targets.retention}%</strong></div><div><span>Complétion</span><strong>≥ {targets.completion}%</strong></div><div><span>Vues</span><strong>≥ {fmt(targets.views)}</strong></div></div></article></section></>}
 {view==="dossiers"&&<section className="panel"><div className="panel-heading"><div><p>ÉVOLUTION</p><h2>001 → {latest?.dossier||"—"}</h2></div></div><div className="dossier-grid">{dossiers.map((d,i)=>{const prev=dossiers[i-1];const delta=prev?((d.views-prev.views)/Math.max(prev.views,1))*100:null;return <article className="dossier-card" key={d.dossier}><div><Badge tone={i===dossiers.length-1?"danger":""}>DOSSIER {d.dossier}</Badge><Ring value={d.score}/></div><h3>{d.title}</h3><p>“{d.hook}”</p><dl><div><dt>Vues</dt><dd>{fmt(d.views)} {delta!==null&&<small className={delta>=0?"up":"down"}>{delta>=0?"+":""}{delta.toFixed(0)}%</small>}</dd></div><div><dt>Hook</dt><dd>{pct(d.scrollStop)}</dd></div><div><dt>Rétention</dt><dd>{pct(d.retention)}</dd></div><div><dt>Complétion</dt><dd>{pct(d.completion)}</dd></div></dl></article>})}</div></section>}
 {view==="videos"&&<section className="panel"><div className="panel-heading"><div><p>DONNÉES BRUTES</p><h2>Résultats par plateforme</h2></div></div><div className="table-wrapper"><table><thead><tr><th>Dossier</th><th>Plateforme</th><th>Vues</th><th>Hook</th><th>Rétention</th><th>Complétion</th><th>Engagement</th><th>Score</th></tr></thead><tbody>{enriched.map(v=><tr key={`${v.platform}-${v.id}`}><td><b>N°{v.dossier}</b><span>{v.title}</span></td><td><Platform name={v.platform}/></td><td>{fmt(v.views)}</td><td>{pct(v.scrollStop)}</td><td>{pct(v.retention)}</td><td>{pct(v.completion)}</td><td>{pct(v.engagement)}</td><td><strong className={v.score>=70?"hot":""}>{v.score}/100</strong></td></tr>)}</tbody></table></div></section>}
 {view==="ai"&&<><section className="strategy-grid">
<article className="strategy-card"><span>HOOK</span><strong>{pct(latest?.scrollStop)}</strong><Badge tone={Number(latest?.scrollStop)>=50?"success":"danger"}>{Number(latest?.scrollStop)>=50?"SOLIDE":"PRIORITÉ N°1"}</Badge><p>Capacité à arrêter le scroll.</p></article>
<article className="strategy-card"><span>MONTAGE</span><strong>{pct(latest?.retention)}</strong><Badge tone={Number(latest?.retention)>=85?"success":"warning"}>{Number(latest?.retention)>=85?"EXCELLENT":"À OPTIMISER"}</Badge><p>Rétention après l'ouverture.</p></article>
<article className="strategy-card"><span>DIFFUSION</span><strong>{fmt(latest?.views)}</strong><Badge tone="warning">VUES</Badge><p>Performance observée du dossier.</p></article>
<article className="strategy-card mission"><span>MISSION D{targets.dossier}</span><strong>≥ {targets.scrollStop}%</strong><Badge tone="danger">HOOK</Badge><p>Sans descendre sous {targets.retention}% de rétention.</p></article>
</section>
<section className="two-column"><article className="panel"><div className="panel-heading"><div><p>ASSISTANT STRATÉGIQUE</p><h2>Verdict Dossier {latest?.dossier}</h2></div></div><button className="primary" onClick={runAnalysis} disabled={analyzing}>{analyzing?"Analyse en cours...":"Analyser toutes les données"}</button><div className="analysis-box">{analysis||`Lecture automatique actuelle : ${diagnosis.message}\n\nAjoute les relevés H+1, H+3, H+6, H+12, H+24 et H+48 pour analyser aussi la trajectoire de diffusion.`}</div></article>
<article className="panel"><div className="panel-heading"><div><p>TRAJECTOIRE DU DERNIER DOSSIER</p><h2>Checkpoints enregistrés</h2></div><Badge tone="success">{snapshots.filter(x=>x.dossier===latest?.dossier).length} relevés</Badge></div>
<div className="snapshot-mini">{snapshots.filter(x=>x.dossier===latest?.dossier).sort((a,b)=>Number(a.hours)-Number(b.hours)).map(x=><div key={x.id}><b>H+{x.hours}</b><span>{fmt(x.views)} vues</span><span>{pct(x.scrollStop)} hook</span><span>{pct(x.retention)} rétention</span></div>)}</div>
<a className="snapshot-link" href="/admin">+ Ajouter un checkpoint H+</a></article></section></>}
 {view==="hooks"&&<section className="panel"><div className="panel-heading"><div><p>HOOK LAB</p><h2>Classement par arrêt du scroll</h2></div></div><div className="hook-list">{[...dossiers].sort((a,b)=>Number(b.scrollStop||0)-Number(a.scrollStop||0)).map((d,i)=><article key={d.dossier}><b>#{i+1}</b><div><h3>“{d.hook||d.title}”</h3><p>Dossier {d.dossier} · {fmt(d.views)} vues · {pct(d.retention)} de rétention après le hook</p></div><div className="hook-score"><strong>{pct(d.scrollStop)}</strong><small>ont continué</small></div></article>)}</div></section>}
 {view==="alerts"&&<section className="two-column"><article className="panel"><div className="panel-heading"><div><p>SEUILS V4</p><h2>Règles de performance</h2></div></div>{[["Hook",latest?.scrollStop,50],["Rétention",latest?.retention,80],["Complétion",latest?.completion,60]].map(([label,value,goal])=><div className="rule" key={label}><span>{label} · {pct(value)} / objectif {goal}%</span><Badge tone={Number(value)>=goal?"success":"danger"}>{Number(value)>=goal?"VALIDÉ":"À TRAVAILLER"}</Badge></div>)}<p className="muted">Les seuils servent à décider quoi modifier sans casser les éléments qui fonctionnent déjà.</p></article><article className="panel target-card"><div className="panel-heading"><div><p>MISSION</p><h2>Dossier {targets.dossier}</h2></div></div><div className="large-alert"><span>🎯</span><h3>Faire passer le hook au-dessus de {targets.scrollStop}%</h3><p>Conserver une rétention d'au moins {targets.retention}%.</p></div></article></section>}
 {!demoMode&&youtube.message&&<div className="system-message">{youtube.message}</div>}</main></div>
}
